### ISSUE TITLE
InciSe logo/icon cannot be brain

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/CaPTk2.0#58]
InciSe logo/icon cannot be brain

**Comment by dboun** [comment]
- The logos should be changed in ```Applications/InciSe/icons```

- Three formats are required (png, ico, icns), but I can do the convertions if we have a png, I did so for CaPTk's icon.

- We need to design an icon

**Comment by dboun** [comment]
As part of PR #56 sample icons were added to test that they show up everywhere we want them to. 

They are temporary until a cool icon design is found

For future reference, starting from a svg image:

```bash
### needs packages: inkscape imagemagick icnsutils
### versions probably won't matter, but for reference:
### Inkscape 0.92.3 (2405546, 2018-03-11)
### (convert->) ImageMagick 6.9.7-4 Q16 x86_64 20170114
### icns2png 1.5

### svg to png
inkscape -z -e icon.png -w 1024 -h 1024 icon.svg
### png to jpg
convert icon.png icon.jpg
### png to ico (128 is kind of the max or something)
convert -resize x128 -gravity center -crop 128x128+0+0 icon.png -flatten -colors 256 -background transparent icon.ico
### png to icns
png2icns icon.icns icon.png
```

**Comment by dboun** [comment]
Turns out that the icons in ```Applications/InciSe``` don't really matter.

Though, I don't really know what changes you did to get the taskbar icon to show up, it will also depend on those.

As it is before these changes, the icon is set by:
```bash
Plugins/org.mitk.cbica.captk.application/src/internal/QmitkCaPTkAppWorkbenchAdvisor.cpp:88:  advisor->SetWindowIcon(":/org.mitk.cbica.captk.application/icon.png");
```
I couldn't find an elegant way to get the productId in the QmitkCaPTkAppWorkbenchAdvisor, so different icons can be set depending on it. The only way I could find to get the productId was ```context->getProperty("blueberry.product").toString();``` in QmitkCaPTkApplicationPlugin, but that leads to nowhere because there is no way to pass it to the QmitkCaPTkAppWorkbenchAdvisor. Creating a separate **plugin** for InciSe application stuff is a solution, but I was hoping to avoid it.
